# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  group: BuildPipelineVariables
  uwpProject: '**/*.wapproj'
  testProject: '**/*.Tests.csproj'
  buildPlatform: 'x86|x64|arm64'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'
  buildFolder: '$(Build.SourcesDirectory)\bin\'

jobs:
- job: Build
  timeoutInMinutes: 120
  steps:

  - task: UseDotNet@2
    displayName: 'Set to use .Net 6.0'
    inputs:
      packageType: sdk
      version: 6.x

  # Run the init.ps1, which mostly restores dependencies
  - task: PowerShell@2
    displayName: 'Restore nuget packages & Monaco editor'
    inputs:
      filePath: 'init.ps1'
      failOnStderr: true

  # Builds the msixbundle file
  - task: MSBuild@1
    displayName: 'Build UWP AppxBundle'
    inputs:
      solution: '$(uwpProject)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/bl:"$(buildFolder)\msbuild.binlog"
                         /t:build
                         /restore
                         /p:AppxBundlePlatforms="$(buildPlatform)"
                         /p:AppxPackageDir="$(appxPackageDir)"
                         /p:AppxPackageSigningEnabled=false
                         /p:AppxBundle=Always
                         /p:UapAppxPackageBuildMode=StoreUpload'
      maximumCpuCount: true

  # Builds unit tests
  - task: MSBuild@1
    displayName: 'Build Unit Tests'
    inputs:
      solution: '$(testProject)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/t:build /restore'
      maximumCpuCount: true

  - task: VSTest@2
    displayName: 'Run Unit Tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\$(buildConfiguration)\**\*.Tests.build.appxrecipe
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      otherConsoleOptions: '/Framework:FrameworkUap10'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      diagnosticsEnabled: True
      collectDumpOn: always

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(appxPackageDir)'
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: output'
    inputs:
      PathtoPublish: '$(buildFolder)'
    condition: failed()
